---
- name: Conditionally load variables
  include_vars:
    file: Ubuntu_greater_than_16.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16'

- debug: var=towercli verbosity=1
  tags: vars

- name: Install Python pip
  become: yes
  apt:
    name: "{{ towercli.pip_package }}"

- name: Install Tower CLI package
  become: yes
  pip:
    name: ansible-tower-cli
    state: latest

- name: Configure Tower CLI access
  template:
    src: .tower_cli.cfg.j2
    dest: "~/.tower_cli.cfg"
    mode: 0600
  no_log: "{{ towercli.no_log }}"
  tags: config
